!!*******************************************************************
!********************************************************************
subroutine mpi_write()
!!*******************************************************************
!********************************************************************
! THIS SUB ROUTINE READES data file generated by matlab. the file has 2d forces on 2d grid. 
! the 2d forces are mapped into 3D grid, then the forces are exported into binary file that suits MPI
USE decomp_2d
USE decomp_2d_io
USE variables
USE param
USE MPI
implicit none
real(8),dimension(ny,NZ) :: FZ2_p,FY2_p,FZ2_n,FY2_n
real(8),dimension(nx,ny,nz) :: FX3_P,FZ3_P,FY3_P,FZ3_N,FY3_N
integer:: i,j,k,COUNT

open(1,file='matlab_force.vrt')

   do K=1,Nz
        Do j=1,NY
	      READ(1,*) FZ2_p(J,K),FY2_p(J,K),FZ2_n(J,K),FY2_n(J,K)	
	!if (nrank.eq.0) print*,k,j
	enddo
	
   enddo
CLOSE (1)

print*, maxval(FZ2_p)
DO I=1,NX
   DO J=1,NY
	DO K=1,NZ          
           FX3_P(I,J,K)=0.0
	   FY3_P(I,J,K)=FY2_P(J,K)
	   FZ3_P(I,J,K)=FZ2_P(J,K)

	   FY3_N(I,J,K)=FY2_N(J,K)
	   FZ3_N(I,J,K)=FZ2_N(J,K)  
	ENDDO
   ENDDO
ENDDO

print*, maxval(FZ3_p)
OPEN(4,FILE='FY_P.dat')
close(4)
open(2,file='FZ_P.dat')
close(2)

OPEN(4,FILE='FY_N.dat')
close(4)
open(2,file='FZ_N.dat')
close(2)

OPEN(4,FILE='FY_P.dat',FORM='UNFORMATTED',ACCESS='DIRECT', RECL=8, STATUS='OLD')
  COUNT = 1     
  DO K=1,nz
     DO J=1,ny
        DO I=1,nx
           WRITE(4,REC=COUNT) FY3_P(I,J,K)
           COUNT = COUNT + 1
        ENDDO
     ENDDO
  ENDDO
 CLOSE(4)

OPEN(4,FILE='FY_N.dat',FORM='UNFORMATTED',ACCESS='DIRECT', RECL=8, STATUS='OLD')
  COUNT = 1     
  DO K=1,nz
     DO J=1,ny
        DO I=1,nx
           WRITE(4,REC=COUNT) FY3_N(I,J,K)
           COUNT = COUNT + 1
        ENDDO
     ENDDO
  ENDDO
 CLOSE(4)

OPEN(5,FILE='FZ_P.dat',FORM='UNFORMATTED',ACCESS='DIRECT', RECL=8, STATUS='OLD')
  COUNT = 1

  DO K=1,nz
     DO J=1,ny
        DO I=1,nx
           WRITE(5,REC=COUNT) FZ3_P(I,J,K)
           COUNT = COUNT + 1
        ENDDO
     ENDDO
  ENDDO
 CLOSE(5)

OPEN(5,FILE='FZ_N.dat',FORM='UNFORMATTED',ACCESS='DIRECT', RECL=8, STATUS='OLD')
  COUNT = 1

  DO K=1,nz
     DO J=1,ny
        DO I=1,nx
           WRITE(5,REC=COUNT) FZ3_N(I,J,K)
           COUNT = COUNT + 1
        ENDDO
     ENDDO
  ENDDO
 CLOSE(5)
end subroutine  mpi_write


!!*******************************************************************
!********************************************************************
subroutine read_force(FY_P,FZ_P,FY_N,FZ_N)
!!*******************************************************************
!********************************************************************

USE decomp_2d
USE decomp_2d_io
USE variables
USE param
USE MPI
implicit none

integer :: i,j,k,irestart,nzmsize,fh,ierror,code
real(mytype),dimension(xsize(1),xsize(2),xsize(3)) :: FX_P,FX_N,FY_P,FY_N,FZ_P,FZ_N
!real(mytype),dimension(Ysize(1),Ysize(2),Ysize(3)) :: FY_P,FY_N
!real(mytype),dimension(Zsize(1),Zsize(2),Zsize(3)) :: FZ_P,FZ_N

integer (kind=MPI_OFFSET_KIND) :: filesize, disp
real(8) lru2
!--------------------------------------------------------------------------------
call MPI_FILE_OPEN(MPI_COMM_WORLD, 'FZ_P.dat',MPI_MODE_RDONLY, MPI_INFO_NULL,fh, ierror)
disp = 0_MPI_OFFSET_KIND
call decomp_2d_read_var(fh,disp,1,FZ_P)
call MPI_FILE_CLOSE(fh,ierror)
if (nrank==0) print *,'read FZ_P.dat file done'
!--------------------------------------------------------------------------------
call MPI_FILE_OPEN(MPI_COMM_WORLD, 'FY_P.dat',MPI_MODE_RDONLY, MPI_INFO_NULL,fh, ierror)
disp = 0_MPI_OFFSET_KIND
call decomp_2d_read_var(fh,disp,1,FY_P)
call MPI_FILE_CLOSE(fh,ierror)
if (nrank==0) print *,'read FY_P.dat file done'
!--------------------------------------------------------------------------------
call MPI_FILE_OPEN(MPI_COMM_WORLD, 'FZ_N.dat',MPI_MODE_RDONLY, MPI_INFO_NULL,fh, ierror)
disp = 0_MPI_OFFSET_KIND
call decomp_2d_read_var(fh,disp,1,FZ_N)
call MPI_FILE_CLOSE(fh,ierror)
if (nrank==0) print *,'read FZ_N.dat file done'
!--------------------------------------------------------------------------------
call MPI_FILE_OPEN(MPI_COMM_WORLD, 'FY_N.dat',MPI_MODE_RDONLY, MPI_INFO_NULL,fh, ierror)
disp = 0_MPI_OFFSET_KIND
call decomp_2d_read_var(fh,disp,1,FY_N)
call MPI_FILE_CLOSE(fh,ierror)
if (nrank==0) print *,'read FY_N.dat file done'
!--------------------------------------------------------------------------------
!print*, maxval(FZ_P),nrank,size(FZ_P),xsize(1),xsize(2),xsize(3)
!lru2=1.
!FZ_P(:,:,:)=FZ_P(:,:,:)*lru2;
!FY_P(:,:,:)=FY_P(:,:,:)*lru2;

end subroutine read_force



!********************************************************************
!!***************************************************************
subroutine PLASMA_FORCE(ux1,uy1,uz1,FY_p,FZ_p,FY_N,FZ_N)
!!***************************************************************
!********************************************************************
USE param
USE variables
USE decomp_2d
USE decomp_2d_io
implicit none
integer :: i,j,k,ii
real(mytype),dimension(xsize(1),xsize(2),xsize(3)) :: ux1,uy1,uz1
real(mytype),dimension(xsize(1),xsize(2),xsize(3)) :: FY_P,FY_N,FZ_P,FZ_N !!!! omar
REAL(8) :: LRU2,f_shap,t_flag,t_flag2


t_flag=sin(2.*pi*v_freq*t*L_CHAR/U_CHAR)

!t_flag=5.
!t_flag2=5.

lru2=L_char/(rho*U_Char**2)/FORCE_COFF ! to nondimensionalize the forces

if (t_flag .Gt. 0.0 ) then
   F_SHAP=1.
   if (nrank .eq. 0) print*,''
   if (nrank .eq. 0) print*, '++++++++++ force direction+++++++++++',F_SHAP,t_flag
   if (nrank .eq. 0) print*,''
!print*, maxval(FZ_P),nrank,size(FZ_P),xsize(1),xsize(2),xsize(3)	
   UZ1(:,:,:)=UZ1(:,:,:)+(FZ_P(:,:,:)*adt(itr)+FZ_P(:,:,:)*bdt(itr))*lru2
   uy1(:,:,:)=uy1(:,:,:)+(FY_P(:,:,:)*adt(itr)+FY_P(:,:,:)*bdt(itr))*lru2

elseif (t_flag .LE. 0.0) then
   F_SHAP=-1
   if (nrank .eq. 0) print*,''
   if (nrank .eq. 0) print*, '------------ force direction -------- ',F_SHAP,t_flag
   if (nrank .eq. 0) print*,''

   UZ1(:,:,:)=UZ1(:,:,:)+(FZ_N(:,:,:)*adt(itr)+FZ_N(:,:,:)*bdt(itr))*lru2
   uy1(:,:,:)=uy1(:,:,:)+(FY_N(:,:,:)*adt(itr)+FY_N(:,:,:)*bdt(itr))*lru2

else 
   F_SHAP=0.
   if (nrank .eq. 0) print*, ' ************ force direction ******** ',F_SHAP,t_flag

endif

end subroutine PLASMA_FORCE


!********************************************************************
!!***************************************************************
subroutine save_old(filename)
!!***************************************************************
!********************************************************************
  !use libmodfilesys_module
  implicit none

  integer :: error
  logical :: exist
  CHARACTER(len=*) :: filename
  !Renaming with error handling
!********************************************************************
!tfilename="time_stats.dat"
  inquire(file=filename, exist=exist)

  if (exist) then
  call rename(filename,'old_'//filename, error)
print*,' Renamed file ', filename,exist
  if (error /= 0) then
    print *, "Error happened in renamming file",filename
    stop
  end if
  endif
end subroutine save_old











